import '@testing-library/jest-dom';
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n.use(initReactI18next).init({
  lng: 'pt-BR',
  fallbackLng: 'pt-BR',
  defaultNS: 'common',
  ns: ['common', 'auth', 'workouts', 'account'],
  resources: {
    'pt-BR': {
      common: {
        brand: 'Treinos',
        save: 'Salvar',
        cancel: 'Cancelar',
        delete: 'Excluir',
        edit: 'Editar',
        loading: 'Carregando...',
        confirm: 'Confirmar',
        back: 'Voltar',
        remove: 'Remover',
        public: 'Público',
        navbar: {
          dashboard: 'Dashboard',
          myWorkouts: 'Meus Treinos',
          account: 'Conta',
          logout: 'Sair',
          themeLight: 'Mudar para Light',
          themeDark: 'Mudar para Dark',
        },
        errors: {},
      },
      auth: {
        signin: {
          heroTitle: 'TREINE\nCOM\nFOCO',
          heroSubtitle: 'Organize seus treinos, acompanhe seu progresso e supere seus limites.',
          heroFooter: 'Organizador de Treinos',
          heading: 'Bem-vindo de volta',
          subheading: 'Entre com seu e-mail e senha',
          emailPlaceholder: 'E-mail',
          passwordPlaceholder: 'Senha',
          submitLoading: 'Entrando...',
          submit: 'Entrar',
          forgotPassword: 'Esqueceu a senha?',
          noAccount: 'Não tem conta?',
          register: 'Registre-se',
          fillAllFields: 'Preencha todos os campos',
        },
        signup: {
          heroTitle: 'COMECE\nSUA\nJORNADA',
          heroSubtitle: 'Crie sua conta e comece a organizar seus treinos hoje mesmo.',
          heroFooter: 'Organizador de Treinos',
          heading: 'Criar conta',
          subheading: 'Preencha os dados abaixo para começar',
          namePlaceholder: 'Nome completo',
          emailPlaceholder: 'E-mail',
          confirmEmailPlaceholder: 'Confirmar e-mail',
          passwordPlaceholder: 'Senha',
          passwordHint: 'Mínimo 8 caracteres, 1 maiúscula e 1 número',
          submitLoading: 'Criando conta...',
          submit: 'Criar conta',
          hasAccount: 'Já tem conta?',
          login: 'Entrar',
          fillAllFields: 'Preencha todos os campos',
          emailMismatch: 'Os e-mails não são iguais',
          passwordMinLength: 'Senha deve ter no mínimo 8 caracteres',
          passwordUppercase: 'Senha deve conter pelo menos uma letra maiúscula',
          passwordNumber: 'Senha deve conter pelo menos um número',
        },
        forgotPassword: {
          heroTitle: 'RECUPERE\nSUA\nSENHA',
          heroSubtitle: 'Sem problema. Enviaremos um link para você criar uma nova senha.',
          heroFooter: 'Organizador de Treinos',
          heading: 'Esqueceu a senha?',
          subheading: 'Informe seu e-mail e enviaremos um link para redefinir sua senha.',
          emailPlaceholder: 'E-mail',
          submitLoading: 'Enviando...',
          submit: 'Enviar link',
          successMessage: 'Se o e-mail estiver cadastrado, você receberá um link para redefinir sua senha. Verifique sua caixa de entrada (e a pasta de spam).',
          backToLogin: 'Voltar ao login',
          rememberPassword: 'Lembrou a senha?',
          doLogin: 'Faça login',
          fillEmail: 'Preencha o e-mail',
          errorSending: 'Erro ao enviar o e-mail. Tente novamente.',
        },
        resetPassword: {
          heroTitle: 'NOVA\nSENHA\nSEGURA',
          heroSubtitle: 'Escolha uma senha forte para manter sua conta protegida.',
          heroFooter: 'Organizador de Treinos',
          heading: 'Redefinir senha',
          subheading: 'Crie uma nova senha para sua conta',
          newPasswordPlaceholder: 'Nova senha',
          confirmPasswordPlaceholder: 'Confirmar nova senha',
          passwordHint: 'Mínimo 8 caracteres, 1 maiúscula e 1 número',
          submitLoading: 'Salvando...',
          submit: 'Redefinir senha',
          backToLogin: 'Voltar ao login',
          invalidLink: 'Link inválido. Solicite um novo.',
          fillAllFields: 'Preencha todos os campos',
          passwordMismatch: 'As senhas não são iguais',
          successMessage: 'Senha redefinida com sucesso! Faça login.',
          expiredLink: 'Link inválido ou expirado. Solicite um novo.',
          passwordMinLength: 'Senha deve ter no mínimo 8 caracteres',
          passwordUppercase: 'Senha deve conter pelo menos uma letra maiúscula',
          passwordNumber: 'Senha deve conter pelo menos um número',
        },
      },
      workouts: {
        home: {
          greeting: 'Olá, {{name}}',
          loadingSubtitle: 'Carregando...',
          subtitle: 'Aqui está o seu próximo treino',
          newWorkout: '+ Novo Treino',
          stats: {
            myWorkouts: 'Meus Treinos',
            exercises: 'Exercícios',
            completed: 'Concluídos',
          },
          emptyTitle: 'Nenhum treino criado ainda',
          emptyDescription: 'Crie seu primeiro treino e comece a organizar seus exercícios',
          createFirst: 'Criar primeiro treino',
          nextWorkout: 'Próximo treino',
          noExercises: 'Nenhum exercício neste treino.',
          startSessionHint: 'Inicie o treino para marcar exercícios',
          endingSession: 'Finalizando...',
          endSession: '⏹ Finalizar Treino',
          startingSession: 'Iniciando...',
          startSession: '▶ Iniciar Treino',
          viewFull: 'Ver completo',
          sessionActive: '🟢 Treino em andamento',
          errorLoading: 'Erro ao carregar dados',
          errorStarting: 'Erro ao iniciar treino',
          errorEnding: 'Erro ao finalizar treino',
        },
        myWorkouts: {
          title: 'Meus Treinos',
          exportingJson: 'Exportando...',
          exportJson: 'Exportar JSON',
          importingJson: 'Importando...',
          importJson: 'Importar JSON',
          newWorkout: '+ Novo Treino',
          loadingWorkouts: 'Carregando treinos...',
          emptyMessage: 'Você não tem treinos ainda. Clique em "+ Novo Treino" para começar!',
          totalCount: '{{count}} treino no total',
          totalCount_plural: '{{count}} treinos no total',
          confirmDelete: 'Tem certeza que deseja deletar este treino?',
          errorLoading: 'Erro ao carregar treinos',
          errorDeleting: 'Erro ao deletar treino',
          errorReordering: 'Erro ao reordenar treinos',
          errorExporting: 'Erro ao exportar treinos',
          editWorkout: 'Editar treino',
          deleteWorkout: 'Excluir treino',
        },
        newWorkout: {
          title: 'Novo Treino',
          workoutNameLabel: 'Nome do Treino',
          workoutNamePlaceholder: 'Digite o nome do treino',
          publicCheckbox: 'Treino Público',
          exercisesLabel: 'Exercícios',
          exerciseNamePlaceholder: 'Nome do exercício',
          removeExercise: 'Remover',
          addExercise: '+ Exercício',
          saving: 'Salvando...',
          saveWorkout: 'Salvar Treino',
          cancel: 'Cancelar',
          nameRequired: 'Nome do treino é obrigatório',
          addAtLeastOne: 'Adicione pelo menos um exercício',
          errorCreating: 'Erro ao criar treino',
        },
        workoutDetail: {
          loadingWorkout: 'Carregando treino...',
          notFound: 'Treino não encontrado',
          back: 'Voltar',
          exportJson: 'Exportar JSON',
          exercisesTitle: 'Exercícios',
          noExercises: 'Nenhum exercício adicionado ainda.',
          addNewExercise: 'Adicionar Novo Exercício',
          exerciseNamePlaceholder: 'Nome do exercício',
          adding: 'Adicionando...',
          addButton: '+ Adicionar',
          deleteExercise: 'Excluir exercício',
          confirmDeleteExercise: 'Tem certeza que deseja deletar este exercício?',
          errorLoading: 'Erro ao carregar treino',
          errorEmptyName: 'Nome do exercício não pode estar vazio',
          errorAdding: 'Erro ao adicionar exercício',
          errorToggling: 'Erro ao atualizar exercício',
          errorDeleting: 'Erro ao deletar exercício',
          errorUpdating: 'Erro ao atualizar exercício',
        },
      },
      account: {
        title: 'Minha Conta',
        subtitle: 'Gerencie seus dados',
        nameLabel: 'Nome',
        emailLabel: 'E-mail',
        saving: 'Salvando...',
        saveChanges: 'Salvar alterações',
        cancel: 'Cancelar',
        updateSuccess: 'Dados atualizados com sucesso!',
        nameRequired: 'O nome não pode estar vazio',
        errorSaving: 'Erro ao salvar',
        changePassword: {
          title: 'Trocar Senha',
          currentPassword: 'Senha Atual',
          newPassword: 'Nova Senha',
          confirmNewPassword: 'Confirmar Nova Senha',
          passwordHint: 'Mínimo 8 caracteres, 1 maiúscula e 1 número',
          fillAllFields: 'Preencha todos os campos',
          passwordMismatch: 'As novas senhas não são iguais',
          saving: 'Salvando...',
          saveButton: 'Salvar Nova Senha',
          cancel: 'Cancelar',
          success: 'Senha alterada com sucesso!',
          error: 'Erro ao mudar senha',
          passwordMinLength: 'Senha deve ter no mínimo 8 caracteres',
          passwordUppercase: 'Senha deve conter pelo menos uma letra maiúscula',
          passwordNumber: 'Senha deve conter pelo menos um número',
        },
        dangerZone: {
          title: 'Zona de Perigo',
          description: 'Esta ação remove permanentemente sua conta e todos os seus dados.',
          deleteButton: 'Deletar Conta',
          modal: {
            title: 'Deletar Conta Permanentemente',
            warning: 'Esta ação é irreversível. Todos seus treinos e dados serão removidos.',
            passwordLabel: 'Digite sua senha para confirmar',
            passwordRequired: 'Digite sua senha',
            cancel: 'Cancelar',
            deleting: 'Deletando...',
            confirmButton: 'Deletar Permanentemente',
            error: 'Senha incorreta ou erro ao deletar conta',
            successMessage: 'Conta deletada com sucesso.',
          },
        },
      },
    },
  },
  interpolation: {
    escapeValue: false,
  },
});
